# Generated by Django 6.0.3 on 2026-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='private_key_pem',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
