# Generated by Django 6.0.3 on 2026-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp', '0002_credential_private_key_pem'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='revocation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
